### ISSUE TITLE
Ajout d'un fichier `requirements.txt` pour gérer les dépendances de l'application Flask

### ISSUE THREAD

**Issue by loicguillois** [Khannasucre/cesi-cubes-iot#5]
Merci pour votre travail sur le projet. Pour améliorer la gestion de votre projet, je vous suggère d'ajouter un fichier `requirements.txt`.

## Pourquoi `requirements.txt` est important :

1. **Gestion des dépendances** : Ce fichier liste toutes les bibliothèques externes nécessaires pour que ton projet fonctionne. Cela assure que quiconque clonant ton projet pourra installer facilement les bonnes versions de ces dépendances.

2. **Reproductibilité** : Avec `requirements.txt`, tu assures que ton projet s'exécutera de manière cohérente sur différentes machines, évitant ainsi les problèmes de "ça marche sur mon ordinateur".

## Comment créer `requirements.txt` :

- Si tu n'as pas encore `pip freeze`, installe-le via pip.
- Active ton environnement virtuel où tu as installé tes dépendances.
- Exécute `pip freeze > requirements.txt` dans ton terminal. Cela créera un fichier `requirements.txt` avec toutes tes dépendances actuelles.

Après avoir créé ce fichier, n'oubliez pas de le pousser sur le dépôt GitHub.

Si vous avez des questions ou besoin d'aide, n'hésitez pas à me le faire savoir !

**Comment by LouGitta** [comment]
Fichier Ajouter

**Comment by LouGitta** [comment]
Requirements.txt ajouter à la racine
