### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by loicguillois** [Khannasucre/cesi-cubes-iot#6]
Détails nécessaires pour la documentation :

1. **Installation et configuration** : Fournir un guide étape par étape pour configurer l'environnement de développement Arduino, installer les packages nécessaires, et configurer les paramètres spécifiques au projet. Vous l'avez fait pour Python et c'est très bien.

2. **Architecture du projet** : Un diagramme détaillant l'architecture logicielle, expliquant comment les différents composants Python et Arduino interagissent au sein de l'application.

3. **Guide d'utilisation des API (bonus)** : Documentation précise sur les endpoints API, les méthodes disponibles, les paramètres attendus, et les formats de réponse. Inclure des exemples de requêtes et de réponses. Vous pouvez utiliser Swagger, exemple : https://datascientest.com/programmer-et-documenter-une-api-avec-python-flask-swagger-et-connexion.

La documentation peut être rédigée en Markdown et ajoutée au dépôt dans un dossier `/docs` ou bien compléter le README.md actuel.

**Comment by LouGitta** [comment]
Refonte du readme pour la doc
